### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Brunex32** [crosire/scripthookvdotnet#1004]
Add a clear and concise description of the feature you have in mind.
We need a new update for the ScriptHookV.Net . A lot of people are requesting it . Please update it .

**Comment by kagikn** [comment]
I’m afraid of tell you that issue is about AB’s Script Hook V, not this Script Hook V .NET, which is dependent on AB’s Hook in calling native functions.
I do not think Script Hook V .NET should be updated as fast as possible, because it seems no memory stuff in this hook messes up.

Let us improve this hook by gain performance or adding more APIs that is convenient but difficult to implement (which might need some disassembling skill) so script developers can make their scripts happier.
