### ISSUE TITLE
There is always an error!

### ISSUE THREAD

**Issue by KHGamerYT** [crosire/scripthookvdotnet#1059]
I need help with ScriptHooknet. I have this weird error when I press F4, it says Failed to write to log file: System.unauthorzed AccessException: Access to the path "C:\Grand Theft Auto V\ScriptHookVDotNet.log" was denied. And then there's another line that says more, where I can't write everything now because it would take too long, so I included a screenshot. Can someone help me please?

Screenshot: https://www.flickr.com/photos/195035573@N05/51892968039/in/dateposted-public/

I use Rockstar Games Launcher for GTA.

**Comment by KHGamerYT** [comment]
And This error!

Screenshot: https://www.flickr.com/photos/195035573@N05/51892980628/in/dateposted-public/

**Comment by kagikn** [comment]
I think your issue happens because your account doesn't have access to write. This is not related to SHVDN in that case.
Usually, the administrator account has write access to the folders in `Program Files`, but regular one don't. I don't have any idea what accounts your GTA folder let write some files, though.
