### ISSUE TITLE
HandlingData inconsistency

### ISSUE THREAD

**Issue by Sardelka9515** [crosire/scripthookvdotnet#1076]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
Which version of SHVDN was the problem encountered with?
3.4.0

**Description**
Add a clear and concise description of what the bug is and how to reproduce it.

Hello
I wrote a simple handling.meta parser, but discovered some problem when comparing the values in handling.meta and the one from `Vehicle.HandlingData`

Below is a simple demonstration:
![image](https://user-images.githubusercontent.com/106232474/179725362-92cbc210-54b3-4fd9-a51f-1c70c9ecf80f.png)

As you can see:
`SuspensionCompressionDamping`, `SuspensionReboundDamping` are 1/10 of their original value from handling.meta
and `AntiRollBarBiasFront`, `SuspensionBiasFront`, `TractionBiasFront`  was multiplied by two when reading from SHVDN,
also`TractionLossMultiplier`, `SteeringLock` don't match.

I'm aware that these values are read/written directly from/to the memory, but the inconsistency between it and handling.meta is a little confusing, maybe you can sanitize them in the getter/setter or at least add some note/comment to the mismatched properties?

**Comment by kagikn** [comment]
Since SHVDN does not alter any handling values, I don't think this issue is not relevant to SHVDN bug if memory offsets are correct. In GTA SA, the game loads handling values from `handling.cfg`, then multiplies or divides some of them before the game put handling values to some memory region. We should have clarify some values can be different from `handling.meta` files, though.

**Comment by kagikn** [comment]
I tested if both `HandlingData.TractionLossMultiplier` and `HandlingData.SteeringLock` point to correct members. Turns out the former is incorrect, which I didn't intend to. Actually the former pointed to the member of `fLowSpeedTractionLossMult`. As for `HandlingData.SteeringLock`, the value (which is in degree) is in radian in a `CHandlingData` instance.
