### ISSUE TITLE
Updates NativeHashes.cs

### ISSUE THREAD

**Issue by Sardelka9515** [crosire/scripthookvdotnet#1109]
Lots of native names have been updated thanks to the GTA6 leak: https://github.com/alloc8or/gta5-nativedb-data/commit/108d7c26cf82a2a89204f184149f8eacded18ce8

I wrote a [simple source generator](https://github.com/Sardelka9515/SHVDN-NativeGen) with support of comments, parameters and return types, all of which are configurable. The [pre-generated file](https://github.com/Sardelka9515/SHVDN-NativeGen/blob/master/SHVDN-NativeGen/NativeHashes.cs) has been tested to compile with existing SHVDN source. 

Lots of warning will be emitted due to the old hash name used all over the scripting API, though. You can generate without **MarkObsolete** flag to suppress that.

**Comment by kagikn** [comment]
We could update `NativeHashes.cs` without worrying about script compatibility. [The last time I updated `NativeHashes.cs`](https://github.com/crosire/scripthookvdotnet/commit/f0ae67bdca30e49434c90b07f6dfb71e38371537), I didn’t care about the obsolete values since enums are compiled as constants and thus removing old values won’t make any compiled scripts incompatible.

**Comment by Sardelka9515** [comment]
Yes, but the V3 API itself uses lots of obsolete names (starting with _*). I assume they'll need to be updated as well?
