### ISSUE TITLE
Update camera postion and rotation while Game.Pause(true)

### ISSUE THREAD

**Issue by MrMois** [crosire/scripthookvdotnet#1201]
# Setup

ScriptHookVDotNet 3.6.0
ScriptHookV 1.0.2845.0
ScriptHookV SDK 1.0.617.1a

# Question

Hello, I am trying to create a freecam which can fly through the world in paused game state (eg. the world is static, no particle movement, no ped movement, no wind effect updates, ...). 

So far I implemented a working freecam, but upon calling Game.Pause(true) the game is not using the updated camera position anymore. I know the position attribute gets updated, because I print it to the screen. I also know the frames get rerendered in paused state, because manual updates like changing a single peds position or deleting all vehicles via script are visible on screen. However the camera perspective does not change. When I enter and leave pause screen with ESC key, the updated camera position is used. So there must be a missing call to transfer the current camera position to the rendering pipeline somewhere.

I think this must be a bug, because going to and then returning from pause menu to game should not alter the screen content. How can I trigger the position update from code?

Note, this is closely related to this old issue https://github.com/crosire/scripthookvdotnet/issues/756, however using Script.Yield() is not an option for me, as it updates the world.

Dummy code:

```
Init:
	World.RenderingCamera = World.CreateCamera(Vector3.Zero, Vector3.Zero, 60.0f)
	Game.Pause(true)

OnTick:
	World.RenderingCamera.Position += Game.LastFrameTime * new Vector3(1, 0, 0) // Not used by pipeline (only when pressing ESC twice)
```

Best, MrMois

**Comment by kagikn** [comment]
I understand why you are trying to achieve, freecam feature would be awesome if the world is static. However, I am confident that the issue lies on the game code, not SHVDN's one.

Find a function that returns the active camera pointer with `0F 29 70 C8 0F 29 78 B8 48 8B F1 44 0F 29 40 A8 E8` (the first call is the one, ripped from Zolika's Trainer), and try messing with the camera matrix when the game is paused with `SET_GAME_PAUSED` (via SHVDN, RPH, or whatever you like to use). You can't see the camera get updated on screen.

**Comment by kagikn** [comment]
I believe you have to directly edit memory to apply the updated matrix of active camera to the screen. You will have to ask how to achieve in other communities such as [5Mods Discord](https://discord.gg/aS3arhM5MY) if you don't have enough skills in disassembling the exe.
