### ISSUE TITLE
Game crashes when inheriting from a class that inherits from Script.

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#133]
I don't know whether this is a bug or a feature but whenever I let a class inherit from a class that inherits from Script the game crashes with an error message
"eine neue Schutzseite für den Stapel kann nicht erstellt werden".
Sorry I don't know the error message in english. I can only translate it literally
"a new protected page for the stack can not be created".
Example:

public class Core : Script
{
   /...
}

internal Class DriverHandling : Core
{
   /...
}

**Comment by crosire** [comment]
It's a feature. But rather than crashing it should only print an error to the log.

**Comment by RainerHilmer** [comment]
Why is that prohibited? I can use dependency injection without any problems though.

public class DriverHandling
{
   Core _core;

   public DriverHandling(Core core)
   {
      _core = core;
   }
}

**Comment by crosire** [comment]
Take your example. You only would want to have DriverHandling executed as script, but Core is a script too. And what if somebody creates an abstract class inherited from script to use that as base, we now have a problem, since we need that constructor. Or if somebody creates two class inherited from a base class inherited from Script and they both use the GUI, how should that be handled? Questions over Questions, so it's easier to just forbid it (and the method used to find Scripts inside the assemblies should actually ignore any classes not directly inherited from Script, so I'm a little confused).

**Comment by crosire** [comment]
Just tried with the latest version and wasn't able to reproduce this. Inheriting a class from a class which inherited "Script" even actually worked.

**Comment by RainerHilmer** [comment]
W00t? I have to try that again. You know, the thing that bugged me was that I just needed the Wait method and had to inherit from Script just for that. Otoh I can understand why it is that way. The .net script hook uses the inheritance for creating threads, right?

**Comment by crosire** [comment]
Correct. Each script runs in its own secure environment (implemented with threads, but it's not multithreading), so an exception won't kill everything.
