### ISSUE TITLE
Auto reload scripts by using FileSystemWatcher

### ISSUE THREAD

**Issue by BenjaminFaal** [crosire/scripthookvdotnet#236]
I got this idea by having to tap INSERT every time i want to test my script.

With inotify its possible to watch files and eventually reload them look at this:

https://msdn.microsoft.com/en-us/library/system.io.filesystemwatcher.aspx?cs-save-lang=1&cs-lang=cpp#code-snippet-2

**Comment by JohnnyCrazy** [comment]
Mh, mixed feelings about this. Some devs may build the new version and copy it over, but still want to test something with the old build before reloading.
if we plan to implement it, devs should be able to enable/disable this feature. (Then we would even need some kind of global settings file)

@crosire ?

**Comment by crosire** [comment]
I had this idea too, but ditched it, because there are times where the user wants to reload the scripts even though she didn't change the code:
* A script crashed and the user wants to restart it.
* The user wants to test something that only happens on script startup
* The user wants to restart a script because it no longer does what he expects
* ...

**Comment by BenjaminFaal** [comment]
Hmm, i understand, these are valid reasons too!

I think with these reasons its better like this indeed. Thanks anyway!

**Comment by crosire** [comment]
=)
