### ISSUE TITLE
Is there a way to pass data and events across scripts without dependencies?

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#330]
I refuse to create mods by writing god classes. I stick with the soc principles. However that makes it necessary to transfer data and even events across classes which inherit from Script. Alas, simple dependency injections seems to cause problems and it's likely the cause for this issue: https://github.com/crosire/scripthookvdotnet/issues/321
So, is there a kind of message bus in ScriptHookVDotNet which I could use?

**Comment by JohnnyCrazy** [comment]
Currently, there is no MessageBus available.
With the implementation of `RequireScript` [here](https://github.com/crosire/scripthookvdotnet/blob/6b49374f829459724db810bec0261eb4f0201c6d/source/Script.hpp#L28) you can depend on other scripts. 

Maybe I misinterpret your wanted practice, but since you can compile to DLLs, you should be able to export events and functions just like you would when writing a library. Then you can just reference the DLL in another project and use their functions. (Of course, you must check if everything which uses native-calls is still running in the correct main-thread)

**Comment by RainerHilmer** [comment]
I uses several classes which inherit from Script in a single mod (which gets compiled). An example for the problem is issue 321. All key events are handled in a KeyHandling class (inherits from Script because of the KeyUp event). Those events call into other classes which also inherit from Script. In case of #321 it's DriverHandling. As soon as I trigger LandAirplane (which calls a native inside), all key events are blocked. Otoh the MenuHandling class (also inherits Script) is not connected to any of the other classes and can be used while the airplane lands. So I suspect it's those dependencies are causing trouble.
I am going to try the RequireScript attribute. Thanks. :)

**Comment by RainerHilmer** [comment]
The RequireScript attribute hasn't changed anything but maybe I am using it wrong. In order to keep with the example above, there is the KeyHandling class and the DriverHandling class. Both inherit from Script. The KeyUp event of KeyHandling gets attached to methods in DriverHandling. So I make an instance of DriverHandling in KeyHandling via Constructor injection. I decorated the KeyHandling class with [RequireScript(typeof(DriverHandling))]. Is this correct?
Looks like I have no other choice than to cram everything into one god class. Bye bye software architecture. :-/

**Comment by RainerHilmer** [comment]
Nevermind, I resolved it now with event based mediators.
