### ISSUE TITLE
Pointer parameters

### ISSUE THREAD

**Issue by AaronJac** [crosire/scripthookvdotnet#377]
Hi,

I'm trying to use this function:
BOOL GET_GROUND_Z_FOR_3D_COORD(float x, float y, float z, float *groundZ,
  Any b) // 0xC906A7DAB05C8D2B 0xA1BFD5E0
But I can't find a way to get the output from the parameter *groundZ.

**Comment by kagikn** [comment]
You can get output arguments with the OutputArgument class.

**Comment by AaronJac** [comment]
Thanks, I'll check it out.

**Comment by JohnnyCrazy** [comment]
If you have more questions, feel free to ask them in the gitter room!

**Comment by RainerHilmer** [comment]
Simply use the generic version of Function.Call:
var groundZ = Function.Call<float>(Hash.GET_GROUND_Z_FOR_3D_COORD, x, y, z);
But why not use the already built in method from the scripthookVdotnet?
World.GetGroundHeight(Vector3 position);
The native function works a bit strange and you must know about it. Whenever the given Z-position is below ground, the function returns 0! So in order to get the right ground value, you better add 1000 to Z before calling it - or you use the GetGroundHeight method. This takes care of this already.
