### ISSUE TITLE
Function::Call<T> not playing well with IntelliSense

### ISSUE THREAD

**Issue by Fireboyd78** [crosire/scripthookvdotnet#430]
Hi, I'm using Visual Studio Community 2015 to work on the project. Everything compiles just fine, but IntelliSense is throwing me errors everywhere when `Function::Call<T>` is used as a return value:

![*sigh*](https://dl.dropboxusercontent.com/u/69162797/screens/intellisense_madness.png)

Game.cpp is so bad it actually crashes IntelliSense!

I'm not sure if anyone else is having this issue, but I think I managed to fix this error by adding an extra overload:

    generic <typename T>
    static T Call(Hash hash, InputArgument ^argument);

Anyone else having this issue? @crosire? This is pretty frustrating, lol.

**Comment by crosire** [comment]
IntelliSense doesn't understand the ```... array<...>``` syntax, which is the C++/CLI equivalent of C#'s ```params``` keyword. The compiler does though. Your suggestion only solves that for native calls with a single argument, IntelliSense will still complain about the rest. There's not much we can do about that, unfrortunately. But since it's just IntelliSense, it's not much of a big issue. Just ignore it or disable IntelliSense errors for the project.

**Comment by Fireboyd78** [comment]
@crosire So you guys get that error too? I was just worried it might be because I'm using Visual Studio 2015 instead of 2013.

**Comment by JohnnyCrazy** [comment]
Yes thats normal @Fireboyd78 , although my editor never crashed because of it.

**Comment by Fireboyd78** [comment]
I'll write a bug report and hope Microsoft can potentially fix this annoying bug. Good to know I'm not the only one experiencing this issue.
