### ISSUE TITLE
Issue with CreatePed(Model model, Vector3 position, Single heading)

### ISSUE THREAD

**Issue by Buuburn** [crosire/scripthookvdotnet#465]
When I try to spawn multiple peds this happens:
System.InvalidOperationException: Illegal call to 'Script.Wait()' outside main loop!
   at GTA.Script.Wait(Int32 ms)
   at GTA.Model.Request(Int32 timeout)
   at GTA.World.CreatePed(Model model, Vector3 position, Single heading)

 But when I use Function.call<Ped>(Hash.CREATE_PED, Etc)  to spawn them it works fine except for a few PedHashes that don't seem to be working. Also using CreateRandomPed() also works.

**Comment by crosire** [comment]
Where do you call ```CreatePed```? The exception explains the problem, it can only be called in one of the events provided by ScriptHookVDotNet (Tick, KeyDown, KeyUp).

**Comment by Buuburn** [comment]
This is the file: https://github.com/RaoulWernert/CodenameMaffia/blob/master/CodenameMaffia/CodenameMaffia/Member.cs at line 36.

**Comment by crosire** [comment]
```CreatePed``` is called through ```Member``` -> ```QuestMember``` -> ```Family.CreateQuestMember``` -> ```Families.Mafia.CreateQuestMembers``` in the constructor of your ```Main``` script. Like I said, it can only be called in the three provided events, not the constructor. This is not supported.

**Comment by Buuburn** [comment]
Is there a reason for that? Why it can only be called in the 3 provided events.

**Comment by zorg93** [comment]
natives can only be called on a GTAnative thread. when a script gets initialised by the .net hook its not currently running on the GTAnative thread

**Comment by crosire** [comment]
It's not about the natives in this case. The constructor is actually called on the thread for native scheduling. The problem is the ```Script.Wait``` function. That one works by pausing the script main loop, which only works if actually inside that said main loop. Since ```World.CreatePed``` internally relies on ```Script.Wait``` to make sure the ped model is loaded into memory before creating it (or else the ped won't spawn), the same restrictions apply here too. That's why you can only call it in one of those three events, which are executed in the script main loop.
