### ISSUE TITLE
Clothing compatibility?

### ISSUE THREAD

**Issue by sollaholla** [crosire/scripthookvdotnet#521]
Something like a struct or class that holds the players clothing? 

```
Clothes clothing = Game.Player.Character.Clothes;
clothing.face_id = 2; //etc.
```

Not sure if already requested sry

**Comment by JohnnyCrazy** [comment]
Propably useful:
http://gtaxscripting.blogspot.de/2016/04/gta-v-peds-component-and-props.html

**Comment by zorg93** [comment]
I had a working clothes editor, but decided to scrap it as some permutations of clothes will cause the game to crash when applied to micheal/franklin/trevor/mp characters(M&F)

**Comment by DorCoMaNdO** [comment]
@zorg93 What do you mean by that? Did you verify that the component IDs/textures are valid? Do certain valid component IDs/textures result the game to crash? cause I haven't experienced that.

I have a working C# coded online-like character creator, letting you customize the components (clothes), overlays (makeup), ped props (accessories), hair styles and colors, eye colors, heritage and facial features (with a grid below the menu, in a similar fashion to Rockstar's online character creator, if you have screenshots of the facial feature settings you can clone the character to singleplayer, and vice versa).
Currently working on tattoos and finding which groups are compatible with eachother so they wouldn't overlap. After that I might add clothing restrictions in a similar fashion to Rockstar's, so you wouldn't have overlapping stuff, but that's a lot of work unless I figure out a better way to do it, so I'll probably only do that if I'm bored.

Also to add to the link from @JohnnyCrazy, watches and bangles are Prop IDs 6 and 7 respectively, at least on the multiplayer models, those aren't mentioned there.

**Comment by zorg93** [comment]
@DorCoMaNdO I just found a specific example then. While playing as franklin, setting the torso drawable to 22(its like a coat), then setting to its max textureID caused the game to crash. As for verification, Im not sure how I could go about that. According to limits set by Number of texture variations it should be ok

**Comment by DorCoMaNdO** [comment]
For verification you'd use natives like IS_PED_COMPONENT_VARIATION_VALID and _IS_PED_PROP_VALID. I'm not sure if it'd keep you away from that scenario though. I've noticed a few odd things myself but not with my code, it was with Menyoo, which uses GET_NUMBER_OF_PED_DRAWABLE_VARIATIONS and GET_NUMBER_OF_PED_TEXTURE_VARIATIONS to check whether there are more drawables or textures to cycle through. I'm not sure whether these will let you avoid the crashes.

**waits to test before sending**

I just tested the torso drawable 22, with Menyoo it lets me to go up to texture 4, which was invisible, it didn't crash until I left it on it for a few seconds. My code, which uses the IS_PED_COMPONENT_VARIATION_VALID native, it goes up to texture 3, texture 4 and up return false (i.e. invalid).

**Comment by zorg93** [comment]
Hmm I didnt know about the variation valid native, adding that check should hopefully fix issues

**Comment by DorCoMaNdO** [comment]
These are snippets from my code but here's how I do it, the API I made handles and verifies everything I've already implemented.

The code below is a snippet of my own menu code, it checks if the current drawable + 1 if pressed numpad right or - 1 if pressed numpad left is valid.

`if (CharacterAPI.IsComponentVariationValid(Target, Component.Mask, drawable + (e.Type == ItemActivatedEventArgs.ActivationType.Left ? -1 : 1)))`
`                            {`
`                                drawable += e.Type == ItemActivatedEventArgs.ActivationType.Left ? -1 : 1;`
`                                texture = 0;`
`                            }`
`                        CharacterAPI.SetComponentVariation(Target, Component.Mask, drawable, texture);`

The function that handles the native:
`public static bool IsComponentVariationValid(this Ped ped, Component component, int drawable, int texture = 0)`
`        {`
`            return Function.Call<bool>(Hash.IS_PED_COMPONENT_VARIATION_VALID, ped, (int)component, drawable, texture);`
`        }`

Component is an enum, I included lots of duplicates to cover what people might think the component is (since on freemode characters some stuff is different), it's understandable if you'd only like the actual names without the duplicates.
`public enum Component : int`
`    {`
`        Head = 0,`
`        Mask = 1,`
`        Beard = 1,`
 `       Hair = 2,`
`        Gloves = 3,`
`        Torso = 3,`
`        Pants = 4,`
`        Legs = 4,`
`        Parachute = 5,`
`        Hands = 5,`
`        Shoes = 6,`
`        Feet = 6,`
`        Accessories = 7,`
`        Scarf = 7,`
`        Necklace = 7,`
`        Bracelet = 7,`
`        Teeth = 7,`
`        Eyes = 7,`
`        Undershirt = 8,`
`        Accessory = 8,`
`        BodyArmor = 9,`
`        Task = 9,`
`        CrewEmblem = 10,`
`        Top = 11,`
`        Shirt = 11,`
`        Torso2 = 11`
`    }`

The function setting a component:
`public static bool SetComponentVariation(this Ped ped, Component component, int drawable, int texture = 0, int palette = 0)`
`        {`
`            if (IsComponentVariationValid(ped, component, drawable, texture)) return false;`

`            Function.Call(Hash.SET_PED_COMPONENT_VARIATION, ped, (int)component, drawable, texture, palette);`

`            return true;`
`        }`

I only added the return values to the set function yesterday, but that lets you simplify the implementation I made in my menu further, instead of checking whether the variation is valid, you could just attempt to set it, if it was successful you could continue to do whatever (in my case it'd be storing the component in the outfit to a file).

**Comment by zorg93** [comment]
I decided to make put Clothes and Ped Props in the same class. The classes for getting and setting Clothes and Props both inherit from the same class as well to make working with them much simpler
