### ISSUE TITLE
Natives performance

### ISSUE THREAD

**Issue by Rbn3D** [crosire/scripthookvdotnet#620]
Hi,

I'm developing a custom vehicle camera mod, and after doing some performance tracing, looks like calling natives is pretty slow. 

Looks like each native call is taking around 26ms/40ms... Calling a few of them each frame hurts performance. Natives like e.g. checking if the player is in a vehicle.

Looks like [this line](https://github.com/crosire/scripthookvdotnet/blob/8c5b75572fd1ceb91b2e13bc7a5b4316c0438ddc/source/core/ScriptDomain.cpp#L703) is the responsible.

So, each time I call a native a task is created, then it waits some time (I guess for thread sync stuff but I don't know) and then gets executed. Of course synchronously, and blocking the whole script.

But a few lines above, i see this:

```cs
if (Thread::CurrentThread->ManagedThreadId == _executingThreadId) {
     task->Run();
```

In this case, task execution should be faster I guess, but my code doesn't do it in that way.

Is there anything that I can do to make my script to perform better? Especially when dealing with natives, I mean.

Is coming any update of SHVDN 2.9.x that would improve natives performance? It's 'fixable', or just not possible?

Thank you for your work 👍

**Comment by crosire** [comment]
That's not what's happening. SHVDN executes every script in a seperate managed thread, so if a script locks up, it doesn't actually crash the game, but is safely aborted after a certain timeout. Since natives can only be called in the main thread, SHVDN uses a task queue to communicate between the script threads and the main thread. When you call a native, the relevant task is send to the main thread, then the script thread waits for the main thread to finish executing it and continues. It's not possible to bypass that from a script.

**Comment by Rbn3D** [comment]
Thanks for the answer.

I'm finally porting my mod to C++, not sure if this is a strong performance boost, but looks like my C++ port performs better. I also feel less limited than in a managed environment.

Since .net is JIT compiled, I'm not sure what is causing this performance drop... Going managed implies less performance? Maybe GC also affects performance.

**Comment by Guad** [comment]
When I needed performance I added a way to call natives in batches in my local fork. That gave a huge performance boost, but you won't be able to get the result from the natives (without overcomplicating everything), so it's not a catch-all fix.

**Comment by crosire** [comment]
We could maybe batch together certain natives that don't return anything (and have no output arguments). But that would possibly screw up the order at which they are invoked and change behavior in unwanted ways.

**Comment by Guad** [comment]
Only if you make it opt-in. Spending hours debugging your script only to find out your critical native got batched sounds really painful.
IMO a separate way to call & batch natives would be the best approach.

**Comment by zorg93** [comment]
26-40ms is definitely wrong when you consider a typical frame is 16ms

**Comment by Rbn3D** [comment]
Maybe slower because of tracing... I'm not sure

**Comment by crosire** [comment]
How did you come by your numbers in the first place? They do indeed sound implausible.

**Comment by zorg93** [comment]
tracing wont explain how 1 single native call is taking longer than it takes the game to push each frame on normal workloads

**Comment by Rbn3D** [comment]
I'm not really sure what's happening (sorry if these are wrong) but I did a trace with JetBrains dotTrace, and in the call stack I found that 26-40ms time. My game it's usually between 50-60 fps but sometimes drops to 30-35. Looks like calling lots of natives hurt performance, even simple ones. But, obviously, mostly anything you do in SHVDN is calling natives under the hood, so it cannot take 26-40ms each one if the game runs at 30-35 fps.

Sorry again.

**Comment by codecat** [comment]
Hi! We noticed this same issue while working on GTMP way before this Github issue was even made and started thinking about possible solutions (aside from the hacky native grouping workaround mentioned in this thread). So I started working on an experimental fork. I've wanted to post my fork for SHVDN as soon as I saw someone else having the exact same issues, but we wanted to wait until I got GTMP working stable on it.

I left (or currently taking a long break) from the GTA modding community, so I've decided to open source my fork (actually a complete rewrite of the C++ core).

**SHVDNPro**: https://github.com/codecat/SHVDNPro

Thus far, early results with our in-house profiler are showing a performance improvement of **14 times the framerate** of regular SHVDN while in the GTMP main menu (which is @Guad's TabMenu in NativeUI) but I believe this can definitely be improved a lot more.

## ScriptHookVDotNet
![](https://i.imgur.com/S57XmRz.png)

## SHVDNPro
![](https://i.imgur.com/eY5lSb1.png)

This fork should work fine for most mods. We've had a few stability issues with GTMP that made the game crash, but I tracked that down to having something to do with our Clearscript/v8 implementation (looks like something isn't resolving the library paths correctly or something, so that should be a relatively easy fix).

I'm Miss#4192 on GTMP's Discord if anyone has any urgent issues or questions with this.

**Comment by Rbn3D** [comment]
@codecat Wow! These are definitely good news!

I'll try this soon.

**Comment by alexsantiago21** [comment]
I can't find the file

**Comment by codecat** [comment]
What do you mean? I haven't uploaded any pre-compiled binaries if that's what you're looking for. You'll have to compile it yourself.

**Comment by Rbn3D** [comment]
@codecat I've tested SHVDNPro, and it's amazing! Didn't do a full performance comparison, but it feels faster!

If you provide downloadable or redistributable binaries, I would be very happy to release my mod targeting SHVDNPro.

I think you should mention that SHVDNPro targets only 3.0, because when I ported my mod from SHVDN 2.9.x I didn't even know I was targeting a different version.

Only one issue, When you press ALT+TAB in GTA V and switch to another application, after some time, if you return to GTA V the game freezees forever, it doesn't even let you switch to another window properly... and crashes after some time. If you could fix this would be nice! I will open an issue in your repo about this.

**Comment by zorg93** [comment]
@codecat props on the performance gains, however I feel like you tackled it the wrong way. Creating additional Threads in SHV doesn't seem necessary and causes issues with things like reloading scripts. The scripts should be able to all share the same NativeThread without the issues that are currently here with them having to wait to switch to the NativeThread. If you could assign a fiber to each GTA::Script and just use fibers to run each of them(fibers that are executing on the NativeThread) then it should solve all issue

**Comment by codecat** [comment]
@zorg93 You are correct, I considered doing that earlier, but went with my initial idea to see how well it would work. Doing it in a single SHV script should be able to work fine as well of course, just requires a little bit different bookkeeping. 👍 

I don't think I'll be doing any more commits to this for a while - like I explained - I'm taking a break from the whole GTA modding stuff. 😢 Do with my fork as you wish. (I might accept pull requests if anyone wants to poke around I guess)

**Comment by zorg93** [comment]
@codecat I feel like it would take me time that i dont have to learn and adapt the codebase

**Comment by codecat** [comment]
Oh that was more a reply for @Rbn3D actually. I forgot the @ mention there. But if you did have time, you'd be more than welcome of course.. 😊

**Comment by Rbn3D** [comment]
@crosire @zorg93 Any plains to make SHVDN call natives directly?

I'm currently targeting SHVDNPro, but I don't want my users to have 2 different Script Hooks that probably aren't compatibles... Don't want to make them to lose all their actual SHVDN mods just to install my mod...

Performance is important so, I guess you can look at it in the future, maybe after 3.0 is released.

**Comment by zorg93** [comment]
@Rbn3D If performance is getting to be a big issue, I'd advise rewriting your mod in c++, can't get faster than that

**Comment by Rbn3D** [comment]
@zorg93 I'll keep targeting SHVDNPro then, but I probably never release it because people wouldn't want issues with multiple SHVDN implementations.

**Comment by DurtyFree** [comment]
I think adding the possibility to run a collection of natives will already greatly help here.

**Comment by DurtyFree** [comment]
Is this still a thing @crosire ?

I know this will greatly improve the performance if its properly done.

**Comment by codecat** [comment]
I made a new `shvdn3` branch on my fork to update to the latest scripting changes, here's the commit: https://github.com/codecat/SHVDNPro/commit/9f0db711c395c71be14adbdcb1ad47db07910680

Completely untested. I'm getting @DurtyFree to test this hopefully later tonight, but if anyone else feels so inclined let me know if this works.

I don't have GTA installed right now so I can't test this.

**Comment by codecat** [comment]
Okay, I tested it, fixed it, and merged a more updated codebase into the [SHVDNPro master branch](https://github.com/codecat/SHVDNPro) now, if anyone cares.

**Comment by kagikn** [comment]
Another thing that can cause performance issue for GC pressure. `InputArgument` is defined as a class in all the version. Because of this, a bunch of heap allocations happen in almost all cases when calling natives, although `InputArgument` will be short-lived and stores only one `ulong` values.
If we bump up the major version to v4, we should define `InputArgument` as a struct (we could make `InputArgumentStruct`, but that will make it inconvenient for script developers because of ambiguous conversions).

**Comment by Sardelka9515** [comment]
> If we bump up the major version to v4, we should define InputArgument as a struct (we could make InputArgumentStruct, but that will make it inconvenient for script developers because of ambiguous conversions).

In that case, stackalloc and argument copy can be skipped as well when executing `NativeTaskArgs`, because arguments are pushed to the stack in a sequential fasion, simply taking the address of the first argument works for me

https://github.com/Sardelka9515/scripthookvdotnetcore/blob/57ad9ca1b6c297de47ff9ef6ce78f7ccf6f4329d/src/ScriptHookVDotNetCore/Scripting/Generated/Function.Overloads.cs#L162

**Comment by crosire** [comment]
Closing, since the original issue outlined here was solved by the addition of the `NoScripThread` script attribute (035d9918d5ee295344e8c9f4200d56300679207d).

**Comment by kagikn** [comment]
Wait, without `NoScriptThread`, I think we could improve performance of native calls by fetching the system memory allocator pointer and fetch active `scrThread` (or `gtaThread`) pointer from TLS of the main SHVDN thread to that of a script thread when needed. MulleDK19 said like this in August 3rd, 2020 (in UTC) in RPH Discord server.
> In the very early days of RPH1 (probably even before first release), we used to remote native calls to the main app domain since they need TLS of the game's main thread (and the core's thread runs on the game's main thread)). But we quickly changed that, and now simply inject TLS into the calling plugin thread on native calls. (And other calls that need the game's main thread TLS)

Since one SHVDN script will be allowed to run at the same time, I think we don't need to worry about thread safety.

The system memory allocator pointer will be needed because some natives will allocate additional memory. [alexguirre](https://github.com/alexguirre) said like this in RPH Discord server:
> the game uses thread local storage (TLS) to store some data that can be different in each thread, for example a pointer to the memory allocator. So some natives may work in any thread because they don't access TLS but other natives will, for example,  try to allocate some memory, get the allocator from TLS and, since in your thread it's null, the game crashes.
You can setup the TLS in your thread by copying the TLS pointer from the main thread to yours or only the offsets that are used in the native you want to call (there's been some discussion in the past in this channel, search for TLS) and it shouldn't crash anymore, but the code may still not be thread-safe since R* only expected the natives to be called from a single thread.

We know memory patterns for 2 offsets.
https://github.com/citizenfx/fivem/blob/f9578a0c545cd8e3f76c7777118e698e1c39a849/code/components/rage-allocator-five/src/sysAllocator.cpp#L39
https://github.com/citizenfx/fivem/blob/f9578a0c545cd8e3f76c7777118e698e1c39a849/code/components/rage-scripting-five/src/scrEngine.cpp#L587

We could use that good-old thread switching as a fallback, though.

**Comment by Sardelka9515** [comment]
How about straight-up hooking `TlsGetValue` and `TlsSetValue`,  redirect the them to the game thread's TEB? It should work for all tls, no need to find offset for each one. The only concern is that .NET might use TLS internally.

**Comment by kagikn** [comment]
For those who wondering if SHVDN uses a trick with TLS by swapping the TLS pointer on the fly like RAGE Plugin Hook does, #1172 makes SHVDN use it and the PR improves performance as there's no need to thread switching just for a single native call no more.
