### ISSUE TITLE
Any way to add ammo to weapon with special rounds from gunrunning?

### ISSUE THREAD

**Issue by TheChilliPL** [crosire/scripthookvdotnet#674]
If player has weapon with special rounds, how can I add ammo to it?

**Comment by DeathOverload** [comment]
I run into the same problem of my spawner. I finally found out the cause and a solution after my research that I wrote C++ code in order to directly access and confirm behaviors of native functions.

As a result, Weapon.Ammo setter doesn't work for special ammo before calling ADD_AMMO_TO_PED native function. This is not a matter of Script Hook V .NET but the native functions SET_PED_AMMO, GIVE_WEAPON_TO_PED and GIVE_DELAYED_WEAPON_TO_PED.

Here's a sample code that special ammo will be added correctly. A key point is the line number 17.

```
001 private void TestSetSpecialAmmo()
002 {
003     const WeaponHash        WH = WeaponHash.HeavySniperMk2;
004     const WeaponComponent   WC = WeaponComponent.HeavySniperMk2ClipExplosive;
005 
006     Ped pedPlayer = Game.Player.Character;
007 
008     if (pedPlayer.Weapons.HasWeapon(WH)) {
009         pedPlayer.Weapons.Remove(WH);
010     }
011 
012     Weapon wp = pedPlayer.Weapons.Give(WH, 0, false, false);
013 
014     wp.SetComponent(WC, true);
015 
016     // Call ADD_AMMO_TO_PED native function as an activator before setting special ammo
017     Function.Call(Hash.ADD_AMMO_TO_PED, new InputArgument(pedPlayer), new InputArgument(WH), new InputArgument(0));
018 
019     wp.Ammo = wp.MaxAmmo;
020 }
```
