### ISSUE TITLE
plss UPDATE

### ISSUE THREAD

**Issue by Gokuzim** [crosire/scripthookvdotnet#739]
I know that GTA V update was big, but i need mods xD, plss update

**Comment by kagikn** [comment]
Come on, don't make issues to complain about not updating SHVDN (this plugin) before Script Hook V (SHV) is updated.
We need to do some tests because the vehicle class (CVehicle) was changed at least. I can test with RPH and update some vehicle memory offsets, but we should test entire SHVDN system after SHV gets updated.
