### ISSUE TITLE
GTA.Native.?A0x55605b1d.NativeTask.Run() error 

### ISSUE THREAD

**Issue by ZeroSuf3r** [crosire/scripthookvdotnet#761]
Full logs from event viewer:
https://pastebin.com/KAhw3npa

Installed mods:
EnableMPCars.asi
EnhancedNativeTrainer.asi
OpenIV.asi
ScriptHookVDotNet.asi
LivelyWorld (scripts folder)
VAutodrive (scripts folder)

Game version: 1.41

Checking ScriptHookVDotNet2.log file, shows VAutodrive script error which indicates that i don't have NativeUI in scripts folder. (Now installed)

**Comment by Dilapidated** [comment]
Pretty positive that this is related to the issue here. https://github.com/crosire/scripthookvdotnet/issues/697#issuecomment-334981553

Most likely its from LivelyWorld as Eddlm also uses a lot of IsPersistent = false while creating vehicles/peds. (though the crash seems to only happen when marking peds IsPersistent = false not vehicles).
