### ISSUE TITLE
scripthook v needs update

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [crosire/scripthookvdotnet#778]
as the game updated today scripthook v no longer works

**Comment by sirjake1990** [comment]
Hey! So sorry I'm new here, but I added the new game file version # to the version enum and opened up my local GTAV and it doesn't seem to be having any issues. Is there a more formal check to see if there's any additional code changes that are needed?

**Comment by Gamedev1909** [comment]
Im hoping its just a version check but can you send me the modded version to gamedev1909@gmail.com

**Comment by nuvious** [comment]
Saw the same issue today. @sirjake1990 , what enumeration did you modify? I found one in the include/main.h of the SDK and added VER_1_0_1365_1_STEAM(NOSTEAM) respectively, but I think the call that's actually throwing the fatal error is in the ScripthookV.dll that gets installed in the game directory and modifying the SDK is moot. I saw that dev_3 had added the 1.0.1365.1 version to their list but that isn't fixing it for me unfortunately.

**Comment by sirjake1990** [comment]
Hey @nuvious. I updated the GameVersion enum within GameVersion.cs inside the scripthookV source (that's the dev_3 change you saw) but a new DLL on the dev-c hasn't been released yet, I'm not sure of the release process. Building the DLL locally got GTAV to open for me however the ASIs were failing to load and unfortunately I don't have enough experience in determining if it was still due to something else within scripthookV or if the ASIs need to update something to load properly. I'm not sure how to debug/troubleshoot scripthookV loading with a game client at the moment.
