### ISSUE TITLE
Script Hook V Critical Error

### ISSUE THREAD

**Issue by Doitforstate** [crosire/scripthookvdotnet#800]
I have not seen this error anywhere else and is only applied when I have Scripthookvdotnet inside my game directory. I'm new to modding as until recently. Whenever I go to load up the game with Scripthookvdot net inside, I get the error title "SCRIPT HOOK V CRITICAL ERROR" and the description "FATAL: CAN'T FIND NATIVE 0x27CD91E03FF596E2". I have my Native UI inside my Visual Studio 2017 and seen people say to have it in 2013-2015 but haven't been updated since 2015. I don't have Visual Studio 2013 or 2015 so I decided to put it inside my 2017 folder. My game is up to date and I have no problems with the other Script Hook V for mods that don't need to be inside the script folder.

**Comment by RainerHilmer** [comment]
"Can't find native" has nothing to do with Native UI. All methods  of the game are called "Native Functions" because they are not wrapped into a higher level. Those native functions have hash addresses. These addresses change with each update because the code moves to different places in memory as code gets inserted, changed or removed. That's the reason why Alexander Blade has to always update ScriptHookV. So that error message either indicates you
a) reference a version of ScriptHookV which is not compatible to the game version or
b) you try to run an outdated piece of code which directly calls a native Function via the hash address which has now become invalid or
c) you found a shdvn method which ceased to work.
