### ISSUE TITLE
Scripthookvdotnet update

### ISSUE THREAD

**Issue by xactigaming** [crosire/scripthookvdotnet#830]
Hello,

I was wondering when the scripthookvdotnet is getting updated because it's almost a month ago since the last gta v update. I can't use any scripthookvdotnet required mods so I can't use the zombie mod with the new arena war vehicles. :(

**Comment by kagikn** [comment]
We're very sorry for not fast update of SHVDN than before, but I should update some hash such as weapon, weapon component hash and radio enums.

Also, I think I should improve long multibyte string handling and native call performance before releasing next version.

**Comment by xactigaming** [comment]
I understand. Good luck

**Comment by crosire** [comment]
@kagikn Btw., if you download the ScriptHookVDotNet.zip artifact from AppVeyor, delete the release that AppVeyor created and create a new release with the same name/tag from the GitHub page with the artifact downloaded previously, GitHub should show you as author for that release instead of me. Which I think would be fair and less misleading =).

**Comment by kagikn** [comment]
@crosire Understood. Next time I'll do that 😊
