### ISSUE TITLE
No way to reload scripts on master

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#876]
On the new version present on master, there is no way to reload the scripts because the F3 console does not exists and the Insert key does nothing.

**Comment by kagikn** [comment]
Actually the console toggle key is changed to F1 with https://github.com/crosire/scripthookvdotnet/commit/c91e937b904be8a7db5e587bc880f5acaec5bf6e, which confused me.

**Comment by justalemon** [comment]
I tried the F1 console, and...

![image](https://user-images.githubusercontent.com/11861253/63081572-ecd14e00-bf11-11e9-89b8-629e2fad7325.png)

**Comment by kagikn** [comment]
Ah sorry, I forgot `ReloadAllScripts()` is removed and now `Reload()` reloads all scripts in the same way as all the released v2 versions (pressing the insert key). See [this](https://github.com/crosire/scripthookvdotnet/blob/d8ddaad6d87a0e97558f9d9cff6e1c349720c558/source/core/DllMain.cpp#L103).

**Comment by crosire** [comment]
Executing `Help()` lists all registered console commands, which is helpful to get an overview.

**Comment by crosire** [comment]
I changed to F1 because F3 already has a default binding in the game.

**Comment by kagikn** [comment]
Wait, F1 also has the default binding to start recording.
The function keys that don't have any dedault keybinds for the singleplayer mode are F4, F9, F10, F11, and F12.

**Comment by crosire** [comment]
Huh, must have changed that then, it didn't come up for me. F12 is used by Steam for screenshots. F4 maybe?

**Comment by crosire** [comment]
Btw. the reason there is a global `Reload` instead of `ReloadAllScripts` now is that the only way to unload an assembly is to unload the appdomain. So to reload scripts that SHVDN has to reload the entire script domain. `ReloadAllScripts` previously just loaded a new copy of all assemblies each time, which messed up dependencies between scripts (as in they did not work) and meant increasing memory usage with each reload. `Reload` cleans up properly now and dependencies work again.
