### ISSUE TITLE
Patch the game during the loading phase to allow debuggers

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#877]
I don't remember what version it was, but Rockstar has implemented something to forbid any debugger from being attached.

So far, I have been using RPH for bypassing this limitation but I feel that it should be integrated into the SHVDN asi.

If I'm not wrong, @UnknownModder knows what exactly is causing this and how to fix it.

**Comment by crosire** [comment]
I don't think this belongs in SHVDN. It would rather make a good separate ASI mod.

**Comment by E66666666** [comment]
[CamxxCore made such a thing](https://www.gta5-mods.com/scripts/loading-performance-anti-debugger-fix), but I suspect meanwhile the game has been updated and the asi doesn't work any more.

**Comment by kagikn** [comment]
At least in b2802 or later, #976 should be the major factor you can't stably run the game (you will encounter unrecoverable random crashes within few minutes) when you have SHVDN installed and you attach a debugger even with ScyllaHide to disable most of anti-debug features.

**Comment by kagikn** [comment]
Okay, #1167 solves the issue and now you can attach a VS debugger. You definitely want to stop the anti-breakpoint feature working since the game checks against manually stepping through & pausing threads and will crash if detected. 
[ZolikaPatch](https://www.gta5-mods.com/scripts/zolikapatch-v-hq-reflections-crash-fixes-more) will do the job when `RemoveAntiDebugChecks` is enabled.
