### ISSUE TITLE
Created vehicles cannot be made not persistent

### ISSUE THREAD

**Issue by s64d0w** [crosire/scripthookvdotnet#906]
**Version**
v3.0.2

**Description**
Vehicles (and possibly other entities) that have isPersistent set to false never despawn (act as if they were persistent). Looks like IsPersistent doesn't work in this version.

My code:
`Ped player = Game.Player.Character;`
`Vehicle vehicle = World.CreateVehicle(VehicleHash.EntityXF, player.Position, player.Heading);`
`vehicle.PlaceOnGround();`
`vehicle.IsPersistent = false;`

If i left the area and came back, in version v2.10.10 the vehicle would be gone, but now it is still there. This causes the game to now crash with my script that is supposed to spawn a lot of non-persistent vehicles. 
Is there a new way to make vehicles (and possibly other entities) not persistent? (running Script Hook V version v1.0.1868.0)

**Comment by electricman226** [comment]
It looks like this originates from #697. (commits [this](https://github.com/crosire/scripthookvdotnet/commit/9a22d7a))

The problem lies within using `SET_ENTITY_AS_MISSION_ENTITY` in the setter for `IsPersistent`. When passed `false`, it should be calling `SET_ENTITY_AS_NO_LONGER_NEEDED`, which is the only correct way that I know of to make a non-mission entity. v2 did this correctly and so did v3 for some time before this commit it seems.

@Dilapidated was the one who suggested the fix (although didn't author it). I'm mentioning him to see what code he was using to test this, as I can't seem to get his results.

**Comment by s64d0w** [comment]
I did some testing and calling both `SET_ENTITY_AS_MISSION_ENTITY` and `SET_ENTITY_AS_NO_LONGER_NEEDED`, or just `MarkAsNoLongerNeeded()` made the vehicle non-persistent again. 

Only doing `SET_ENTITY_AS_MISSION_ENTITY` (like it is right now) did not make it non-persistent. Not sure why `SET_ENTITY_AS_NO_LONGER_NEEDED` was removed, it looks to me that in #697 Dilapidated said that adding a check would fix crash? don't see anything about removing that native call?

I guess as a temporary workaround I could use `MarkAsNoLongerNeeded()` instead of `IsPersistent = false` since it didn't crash for vehicles anyway

**Comment by electricman226** [comment]
It seems he was wrong. The native `SET_ENTITY_AS_MISSION_ENTITY` takes two unknown parameters, neither of which are a toggle for becoming a mission entity. `SET_ENTITY_AS_NO_LONGER_NEEDED` **is** what makes something non-persistent, so I'm not sure how he came to that conclusion.

I have PR ready that I can submit, I just want to see if there's any other info I'm missing from him.
