### ISSUE TITLE
Remove Map/World Blips on Script Unload/Reload

### ISSUE THREAD

**Issue by SkyEngine-OSP** [crosire/scripthookvdotnet#994]
To begin with, i have a similar issue from 6 years back ([#218](https://github.com/crosire/scripthookvdotnet/issues/218)) but i think its way far back and the solution is perhaps already outdated.

I have a script mod that draws blips into the world. However, my script re-draws those blips over and over again every time the the script is reloaded. This multiplies the legend counter on the map by how many times the script have been reloaded.

Is there any way i can get past this issue? i'm using SHVDN3.

Ta

**Comment by RelaperCrystal** [comment]
Make a list of all your blips created. Then, add event handler for OnAbort event on one of your scripts (or use existing one), add a foreach loop there to validate (blip?.Exists() == true) and delete the blips.

**Comment by SkyEngine-OSP** [comment]
Hi, thanks for that fast reply.

I'm sorry, i'm really new to scripting as i just started yesterday. But, where can i find the OnAbort event and where should i hook it from? is it accessible from the Constructor?

And how exactly can i delete the blips? The Blip object i get from World.CreateBlip doesn't offer any remove/delete function.

Ta

**Comment by RelaperCrystal** [comment]
For the first question, OnAbort event is a non-static event in the script class, which occurs when script is being aborted. For the second question, Blip provides a non-static method called Delete(). Note that these are for APIv3, and if you are using APIv2, I recommend you to update your mod to APIv3.

**Comment by SkyEngine-OSP** [comment]
right, found it before your reply lol. i was typing a wrong keyword. sorry about that mate.

Thanks about the `Blip.Delete()` method, found it too. Now my final concern would be, how would i be able to check if it exists?

From my understanding, `World.CreateBlip()` immediately creates a blip in the World/Map. If that's the case, wouldn't it be too late to check if the Blip already exists because it already made an overlapping duplicate?

Here's a snip of my Blip drawing implementation.
![image](https://user-images.githubusercontent.com/12471935/119214244-ec5ae380-baf7-11eb-8a1f-1ba7a6c2eedb.png)

Really appreciate your help

**Comment by SkyEngine-OSP** [comment]
Thank you very much for helping me out @RelaperCrystal, I'll be sure to put your name on the credits for your kindness :D

**Comment by RelaperCrystal** [comment]
The existence must be checked before you do anything with a handle-able (e.g. everything had a handle) in another tick (e.g. another tick call, yielded/wait-ed your script), means you'll have to validate each tick you do something with that handle-able, however you don't have to check too frequently to the blip unless you do something every tick with blip and it's possible that the blip could be deleted.
For example, you created a blip, added to your list, but later found that you doesn't need that blip to show anymore so you deleted it. 
So when on your cleanup, the cleanup code didn't validate blip when deleting and then it throw an exception because the blip was invalid.
You can only delete or validate a blip if your script does have an instance reference of the blip. When reloading, the instance is automatically removed but the blip didn't. So it's up to you to delete the blips when your script unloads.
Maybe I can't explain this clearly on plain text, so reply if you can't understand something I said.
