### ISSUE TITLE
Why Euphoria funaction is not supported

### ISSUE THREAD

**Issue by oooper666** [crosire/scripthookvdotnet#997]
is been long year why ScriptHookDotNet don't update and fix euphoria Funaction

**Comment by oooper666** [comment]
My game is newest version.

**Comment by Tanjitsu** [comment]
You are welcome to contribute :)

**Comment by kagikn** [comment]
I think I can fix Euphoria stuff now because I found a way to grab a old exe.
I found [a repo for speedrunning that can downgrade to 1.0.372.2 (1.27 in online versioning)](https://github.com/TwosHusbandS/Project-127). I tested the downgraded exe, and the memory patterns for `GiveNmMessageFuncAddress` (`48 8b c4 48 89 58 08 48 89 68 10 48 89 70 18 48 89 78 20 41 55 41 56 41 57 48 83 ec 20 e8 ? ? ? ? 48 8b d8 48 85 c0 0f`) and `CreateNmMessageFuncAddress` (`33 DB 48 89 1D ? ? ? ? 85 FF` - 0x42) work as intended!
Will swap the memory patterns to more future-proofed ones and fix other offsets that are related to Euphoria stuff soon.

**Comment by kagikn** [comment]
Now scripts that use euphoria features will work, I think. [Try this build](https://ci.appveyor.com/project/crosire/scripthookvdotnet/builds/40676336/artifacts) by October 8th.

**Comment by oooper666** [comment]
@kagikn keep crashing when I installed simple trainer

**Comment by kagikn** [comment]
@oooper666 I swapped the link of build to the newest one because some other bug might be crashing your game. Make sure you have the latest Simple Trainer installed (old ones don't work correctly in later game builds if i remember correctly), though.

**Comment by oooper666** [comment]
@kagikn SCRIPT HOOK V CRITICAL ERROR: FATAL: Can't find native 0xF7AF4F159FF99F97

**Comment by kagikn** [comment]
@oooper666 I afraid to say that's not our responsibility. Simple Trainer V is not working for you because [the native function whose hash is 0xF7AF4F159FF99F97 (or _GET_MAKE_NAME_FROM_VEHICLE_MODEL) ](https://alloc8or.re/gta5/nativedb/?n=0xF7AF4F159FF99F97) is only available in v1.0.1868.0 and the trainer calls the function without checking the game version. (3 occurrances of `97 9F F9 9F 15 4F AF F7` in the binary).
An older version of Simple Trainer V like 10.9 might work, but I would say you should use the latest game version unless you know some mods aren't working in later versions (or you're researching exes). Or, **buy a LEGAL copy of GTA V if you don't have one**.

**Comment by oooper666** [comment]
@kagikn i just downgrade not cracked version

**Comment by oooper666** [comment]
@Tanjitsu When I using version 10.9 the script hook say :CORE: An expection occurred while executing 'TrainerV.asi' (0x00007FFAB72A8600), id31

**Comment by kagikn** [comment]
@oooper666 Try older versions than 10.9 if you’ve downgraded on purpose. I think the trainer doesn’t care about older game versions much.
And please, don’t tag irrelevant people.

**Comment by oooper666** [comment]
@kagikn I try all the version is same, also have error

**Comment by kagikn** [comment]
@oooper666 I have no idea then. Could you test mods which uses `GTA.NaturalMotion.Euphoria` such as DrunkIV and PushIV will work for you with the build I pasted without the trainer? I'd like to know these scripts will work in v3.2.0 or later versions of SHVDN.

**Comment by oooper666** [comment]
@kagikn the game crash

**Comment by kagikn** [comment]
I’m not sure Euphoria features still doesn’t work for some people who has a legal copy, but I think we have to see if more people will report Euphoria issues after subsequent official releases of SHVDN.
Euphoria features work for me, so I’m not convinced they still don’t work yet.

**Comment by WithLithum** [comment]
Have you tested on other platform, such as EGS, Retail, or Steam? Which one did you use? Or you use pattern which is usually guaranteed to work on every version?

**Comment by oooper666** [comment]
@kagikn The SHVDN problem, crash when I using newest version SHVDN

**Comment by oooper666** [comment]
Epic

> Have you tested on other platform, such as EGS, Retail, or Steam? Which one did you use? Or you use pattern which is usually guaranteed to work on every version?

Epic

**Comment by oooper666** [comment]
> Have you tested on other platform, such as EGS, Retail, or Steam? Which one did you use? Or you use pattern which is usually guaranteed to work on every version?

Epic

**Comment by kagikn** [comment]
I use Steam versions. I think Euphoria features now work because offsets for them are fetched using memory patterns (they were hard coded before).
Could you test Euphoria features the latest build on AppVeyor, @WithLithum ?

**Comment by oooper666** [comment]
It work on old SHVDN

**Comment by WithLithum** [comment]
I tested on my side. Game doesn't crash and DrunkIV seems work correctly.

**Comment by oooper666** [comment]
what SHVDN version you using

**Comment by WithLithum** [comment]
Like downloaded right now from AppVeyor CI.

**Comment by oooper666** [comment]
it crash when i use it

**Comment by oooper666** [comment]
@kagikn I reinstall many time it just same

**Comment by WithLithum** [comment]
Are you sure you are using AppVeyor version, not release version?

**Comment by oooper666** [comment]
@WithLithum sorry for late reply, yes
